- name: Install i3 window manager
  become: true
  block:
    - name: Download i3 keyring
      command:
        cmd: /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb keyring.deb SHA256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734
      args:
        creates: keyring.deb

    - name: Install i3 keyring
      apt:
        deb: ./keyring.deb

    - name: Add i3 repository
      shell: |
        echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | tee /etc/apt/sources.list.d/sur5r-i3.list
      args:
        creates: /etc/apt/sources.list.d/sur5r-i3.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install i3
      apt:
        name: i3
        state: present
