---
- name: Get lazygit version
  ansible.builtin.command: >
    curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*'
  register: lazygit_version

- name: Get lazygit tarball
  uri:
    url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_release.json.tag_name }}_Linux_x86_64.tar.gz"
    dest: "/tmp/lazygit_{{ lazygit_release.json.tag_name }}.tar.gz"

- name: Extract lazygit from tarball
  ansible.builtin.unarchive:
    src: "/tmp/lazygit_{{ lazygit_release.json.tag_name }}.tar.gz"
    dest: "/tmp"
    extra_opts: [--strip-components=1]

- name: Install lazygit to /usr/local/bin
  become: yes
  ansible.builtin.copy:
    src: "/tmp/lazygit"
    dest: "/usr/local/bin/lazygit"
    mode: "0755"
