---
- name: Setup shell for MacOSX
  import_tasks: macosx.yml
  when: ansible_os_family == "MacOSX"

- name: Setup shell for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
