---
- name: Check current shell
  shell: echo $SHELL
  register: current_shell
  changed_when: false

- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: latest
  when:
    - ansible_distribution == "Ubuntu"
    - "'zsh' not in current_shell.stdout"

- name: Set zsh as default shell
  become: yes
  shell: chsh -s $(which zsh)
  when:
    - ansible_distribution == "Ubuntu"
    - "'zsh' not in current_shell.stdout"

- name: Configure wezterm apt repo
  become: yes
  shell: |
    curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | tee /etc/apt/sources.list.d/wezterm.list

- name: Update apt package list
  become: yes
  apt:
    update_cache: yes

- name: Install wezterm using apt
  become: yes
  apt:
    name: wezterm
    state: latest
